# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release

permissions:
  id-token: write
  contents: write

# trigger by `git tag` push only via `npm release`
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm prepack
      
      - name: Sync changelog from github releases
        run: |
          npx run changelogen --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          file_pattern: 'CHANGELOG.md'
          commit_message: 'chore: generate changelog'
          
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
